#!/usr/bin/env ruby

root = File.expand_path '../database', __dir__

script_filename = 'uninstall.sh'
script_filepath = File.join root, script_filename
system script_filepath

script_filename = 'install.sh'
script_filepath = File.join root, script_filename
system script_filepath
